server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:

        - id: customer-service
          uri: lb://businessdomain-customer
          predicates:
            - Path=/customers/**, /admin/customers/**
          filters:
            - AuthenticationFilter

        - id: cinema-service
          uri: lb://businessdomain-cinema
          predicates:
            - Path=/cinemas/**, /admin/cinemas/**
          filters:
            - AuthenticationFilter

        - id: movie-service
          uri: lb://businessdomain-movie
          predicates:
            - Path=/movies/**, /admin/movies/**
          filters:
            - AuthenticationFilter

        - id: transaction-service
          uri: lb://businessdomain-transaction
          predicates:
            - Path=/transactions/**, /admin/transactions/**
          filters:
            - AuthenticationFilter

        - id: product-service
          uri: lb://businessdomain-product
          predicates:
            - Path=/products/**, /admin/products/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:9091/eureka}
